#mysql
version: '3'
services:
  mysql:
    image: mysql:8.0.35
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: demo

  redis:
    image: redis:6.2.14
    container_name: redis_container
    ports:
      - "6380:6379"
    environment:
      - REDIS_PASSWORD=redis123456